import { type Translations } from './types';
import { LogoIcon } from './components/Icons';

export const serviceIcons = {
    'artTherapy': LogoIcon,
    'speechTherapy': LogoIcon,
    'adultTherapy': LogoIcon,
    'childBehavioralTherapy': LogoIcon,
    'pregnancyEmotionRegulation': LogoIcon,
    'musicTherapy': LogoIcon,
    'movementTherapy': LogoIcon,
    'groupTraining': LogoIcon,
    'ageTherapy': LogoIcon,
    'onlineTherapy': LogoIcon,
    'visitorSupport': LogoIcon,
};

export const therapyServicesData = [
    {
        id: 'artTherapy',
        color: '#a855f7', // purple-500
        duration: '60 Min',
        category: 'Therapy',
        rating: 4.9,
        reviewCount: 78,
    },
    {
        id: 'speechTherapy',
        color: '#22c55e', // green-500
        duration: '45 Min',
        category: 'Therapy',
        rating: 4.8,
        reviewCount: 56,
    },
    {
        id: 'adultTherapy',
        color: '#3b82f6', // blue-500
        duration: '50 Min',
        category: 'Therapy',
        rating: 4.9,
        reviewCount: 132,
    },
    {
        id: 'childBehavioralTherapy',
        color: '#f97316', // orange-500
        duration: '45 Min',
        category: 'Therapy',
        rating: 4.7,
        reviewCount: 95,
    },
    {
        id: 'pregnancyEmotionRegulation',
        color: '#ec4899', // pink-500
        duration: '50 Min',
        category: 'Counseling',
        rating: 4.9,
        reviewCount: 61,
    },
    {
        id: 'musicTherapy',
        color: '#6366f1', // indigo-500
        duration: '60 Min',
        category: 'Therapy',
        rating: 4.8,
        reviewCount: 43,
    },
    {
        id: 'movementTherapy',
        color: '#14b8a6', // teal-500
        duration: '60 Min',
        category: 'Therapy',
        rating: 4.7,
        reviewCount: 39,
    },
    {
        id: 'groupTraining',
        color: '#eab308', // yellow-500
        duration: '90 Min',
        category: 'Training',
        rating: 5.0,
        reviewCount: 35,
    },
    {
        id: 'ageTherapy',
        color: '#ef4444', // red-500
        duration: '50 Min',
        category: 'Therapy',
        rating: 4.6,
        reviewCount: 52,
    },
    {
        id: 'onlineTherapy',
        color: '#0ea5e9', // sky-500
        duration: '50 Min',
        category: 'Therapy',
        rating: 4.8,
        reviewCount: 210,
    },
    {
        id: 'visitorSupport',
        color: '#84cc16', // lime-500
        duration: 'Varies',
        category: 'Counseling',
        rating: 4.9,
        reviewCount: 25,
    },
];

export const faqsData = [
  { id: 1, question: 'faq.1.q', answer: 'faq.1.a' },
  { id: 2, question: 'faq.2.q', answer: 'faq.2.a' },
  { id: 3, question: 'faq.3.q', answer: 'faq.3.a' },
  { id: 4, question: 'faq.4.q', answer: 'faq.4.a' },
  { id: 5, question: 'faq.5.q', answer: 'faq.5.a' },
];

export const testimonialsData = [
  { id: 1, quote: 'testimonials.1.quote', author: 'testimonials.1.author' },
  { id: 2, quote: 'testimonials.2.quote', author: 'testimonials.2.author' },
  { id: 3, quote: 'testimonials.3.quote', author: 'testimonials.3.author' },
];

export const translations: Translations = {
  en: {
    header: {
      visitSite: 'Visit Website',
      contact: 'Contact Us',
      meetTheCEO: 'Meet Our CEO',
      nav: {
        visitorSupport: 'Visitor Support',
      },
    },
    welcome: {
      title: 'Welcome to Your Safe Space for Emotional Healing',
      description: "Not all mental health professionals are called 'doctor' - healing happens in the relationship, not just in the title. Our approach is based on deep presence, evidence-based tools, and lived wisdom.",
      ctaBook: 'Book a Session Now',
      ctaExplore: 'Explore Our Services',
      chatbotGreeting: 'Hello! I am the Relief AI assistant, ready to help you in {{language}}. How can I help you today? I can answer questions about our services, booking, and more.',
    },
    language: {
        english: 'English',
        amharic: 'Amharic',
    },
    services: {
      title: 'Our Professional Services',
      description: 'We offer a wide range of services tailored to meet your unique needs. Our experienced therapists are here to guide you on your journey to mental wellness.',
      priceFlexible: 'Price is Flexible',
      generalInquiry: {
          title: 'General Inquiry',
          description: 'For any questions about our services or how we can help you.'
      }
    },
    service: {
        'artTherapy': { name: 'Art Therapy', short: 'Express and process feelings through creative methods.', description: '...' },
        'speechTherapy': { name: 'Speech Therapy', short: 'Improve communication skills and treat speech disorders.', description: '...' },
        'adultTherapy': { name: 'Adult Therapy', short: 'Individual counseling for adults facing life challenges.', description: '...' },
        'childBehavioralTherapy': { name: 'Child Behavioral Therapy', short: 'Support for children with behavioral and emotional issues.', description: '...' },
        'pregnancyEmotionRegulation': { name: 'Pregnancy Emotion Regulation', short: 'Emotional support for expectant and new mothers.', description: '...' },
        'musicTherapy': { name: 'Music Therapy', short: 'Use music to address physical, emotional, and social needs.', description: '...' },
        'movementTherapy': { name: 'Movement Therapy', short: 'Using dance and movement for emotional and physical integration.', description: '...' },
        'groupTraining': { name: 'Group Training', short: 'Interactive workshops for personal and professional growth.', description: '...' },
        'ageTherapy': { name: 'Age-Specific Therapy', short: 'Tailored therapy for different life stages, from youth to seniors.', description: '...' },
        'onlineTherapy': { name: 'Online Therapy', short: 'Convenient and accessible therapy sessions from anywhere.', description: '...' },
        'visitorSupport': { name: 'Visitor Support & Guidance', short: 'Comprehensive assistance for visitors in Addis Ababa.', description: '...' },
    },
    faq: {
      title: 'Frequently Asked Questions',
      '1': { q: 'What should I expect in my first therapy session?', a: 'Your first session is an opportunity for you and your therapist to get to know each other. You\'ll discuss what brought you to therapy, your history, and your goals. It\'s a collaborative process aimed at building a trusting therapeutic relationship.' },
      '2': { q: 'How long does a therapy session last?', a: 'Typically, individual sessions last for 50 minutes. Couples and family sessions may be longer, around 60-75 minutes, depending on the specific needs and arrangements.' },
      '3': { q: 'Is what I share in therapy confidential?', a: 'Yes, confidentiality is a cornerstone of therapy. Everything you share is kept private, with a few legal and ethical exceptions which your therapist will discuss with you during your first session.' },
      '4': { q: 'How do I book an appointment?', a: 'You can book an appointment by clicking the "Book a Session Now" button on our homepage or by selecting a service and clicking its booking button. This will take you to a form to request your preferred time and date.' },
      '5': { q: 'Do you offer online sessions?', a: 'Yes, we offer both in-person and online (telehealth) sessions to provide flexible and accessible care to our clients, no matter where they are located.' },
    },
    testimonials: {
      title: 'What Our Clients Say',
      '1': { quote: 'The support I received was life-changing. I felt heard and understood for the first time. Highly recommend their services.', author: 'Abebe T.' },
      '2': { quote: 'Our therapist was incredibly skilled at helping us navigate our issues. Our communication has improved immensely.', author: 'Helen M. & Samuel B.' },
      '3': { quote: 'A very professional and warm environment. I was hesitant to start therapy, but the team at Relief made it a comfortable and rewarding experience.', author: 'Fatuma S.' },
    },
    ceoProfile: {
      title: 'A Message From Our CEO',
      name: 'Mrs. Mekdes Ayene',
      role: 'Founder & CEO, Clinical Psychologist',
      message: 'Our mission at Relief is to provide accessible, high-quality mental health care that empowers individuals and strengthens our community. We believe in the resilience of the human spirit and are dedicated to guiding you on your path to wellness.',
      stat1: 'Years of Experience',
      stat1Value: '12+',
      stat2: 'Happy Clients',
      stat2Value: '5,000+',
      stat3: 'Success Rate',
      stat3Value: '98%',
      contact: 'Get in Touch',
    },
    footer: {
      aboutTitle: 'About Relief',
      aboutText: 'Relief Psychological Service is a leading provider of mental health care in Addis Ababa, committed to fostering well-being and personal growth.',
      quickLinksTitle: 'Quick Links',
      linkServices: 'Our Services',
      linkVisitorSupport: 'Visitor Support',
      linkFaq: 'FAQ',
      linkTestimonials: 'Testimonials',
      linkCeoProfile: 'CEO Profile',
      contactTitle: 'Contact Us',
      copyright: '© 2024 Relief Psychological Service. All rights reserved.',
    },
    contactModal: {
      title: 'Get In Touch',
      description: 'Have a question? Fill out the form below to get in touch.',
      email: 'reliefefoyita57@gmail.com',
      phone: '+251932520157',
      form: {
        name: 'Full Name',
        email: 'Email Address',
        message: 'Message',
      },
      submit: 'Send Message',
      submitting: 'Sending...',
      submitError: 'Could not send message. Please try again later.',
      successTitle: 'Message Sent!',
      successMessage: "Thank you for reaching out. We'll get back to you as soon as possible.",
      validation: {
        nameRequired: 'Full name is required.',
        emailRequired: 'Email is required.',
        emailInvalid: 'Please enter a valid email address.',
        messageRequired: 'Message is required.',
        messageMinLength: 'Message must be at least 10 characters long.',
      }
    },
    visitorSupport: {
      title: 'Comprehensive Support for Visitors',
      subtitle: 'Your home away from home in Addis Ababa.',
      description: 'We provide specialized support for short-term visitors, ensuring your stay is comfortable, safe, and psychologically supported. From accommodation assistance to community integration, we are here for you.',
      getStarted: 'Get Started',
      featureTitle: 'What We Offer',
      accommodationTitle: 'Accommodation',
      accommodationDesc: 'Assistance in finding safe and suitable housing (hotels, guesthouses).',
      navigationTitle: 'City Navigation',
      navigationDesc: 'Guidance on transportation, local amenities, and cultural norms.',
      psychologicalTitle: 'Psychological Support',
      psychologicalDesc: 'Access to professional counseling to manage stress and culture shock.',
      communityTitle: 'Community Integration',
      communityDesc: 'Connecting you with local communities and resources to feel at home.',
    },
    accommodationModal: {
        title: 'Accommodation Assistance',
        subtitle: 'Let us help you find the perfect place to stay in Addis Ababa.',
        form: {
            name: 'Full Name',
            email: 'Email Address',
            accommodationType: 'Type of Accommodation',
            types: {
                hotel: 'Hotel',
                guestHouse: 'Guest House',
                apartment: 'Apartment',
            },
            duration: 'Duration of Stay (e.g., 2 weeks)',
            guests: 'Number of Guests',
            area: 'Preferred Area (Optional)',
            budget: 'Budget per Night (Optional)',
            notes: 'Additional Notes or Preferences',
        },
        submit: 'Request Assistance',
        successTitle: 'Request Sent!',
        successMessage: 'Thank you for your request. Our team will review your needs and get back to you with accommodation options within 24 hours.',
        validation: {
            nameRequired: 'Full name is required.',
            emailRequired: 'Email is required.',
            emailInvalid: 'Please enter a valid email address.',
            accommodationTypeRequired: 'Please select an accommodation type.',
            durationRequired: 'Duration of stay is required.',
            guestsRequired: 'Number of guests is required.',
            guestsInvalid: 'Please enter a valid number of guests.',
        },
    },
    bookingModal: {
        title: 'Book Your Session',
        subtitle: 'You are booking a session for:',
        form: {
            name: 'Full Name',
            email: 'Email Address',
            phone: 'Phone Number (Optional)',
            date: 'Preferred Date',
            time: 'Preferred Time',
            notes: 'Notes for the therapist (Optional)',
            sendEmailCopy: 'Send me a confirmation email',
        },
        submit: 'Request Appointment',
        submitting: 'Submitting...',
        submitError: 'Could not send booking request. Please try again later.',
        successTitle: 'Request Submitted!',
        successMessage: 'Thank you for your booking request. A confirmation email has been sent. We will contact you shortly to confirm your appointment.',
        close: 'Close',
        payment: {
            title: 'Payment Information',
            priceEtb: '1,500 ETB',
            priceUsd: '$30 USD',
            methods: 'Accepted Payment Methods',
            telebirr: 'Telebirr',
            telebirrNumber: '0911223344',
            bank: 'Bank Transfer',
            bankAccountName: 'Relief Psychological Service PLC',
            cbe: 'Commercial Bank of Ethiopia (CBE)',
            cbeAccount: '1000123456789',
            cbeSwift: 'CBETETAA',
            abyssinia: 'Bank of Abyssinia',
            abyssiniaAccount: '9876543210',
            abyssiniaSwift: 'ABYSETAA',
        },
        validation: {
            nameRequired: 'Full name is required.',
            emailRequired: 'Email is required.',
            emailInvalid: 'Please enter a valid email address.',
            dateRequired: 'Please select a date.',
            timeRequired: 'Please select a time.',
        }
    },
    categories: {
      all: 'All',
      counseling: 'Counseling',
      therapy: 'Therapy',
      training: 'Training',
    },
    adBanner: {
      text: 'Special Offer: Get 20% off your first online therapy session! Limited time only.',
      cta: 'Learn More',
    },
    auth: {
      login: 'Login',
      signup: 'Sign Up',
      logout: 'Logout',
      loading: 'Loading...',
      loginTitle: 'Welcome Back',
      signupTitle: 'Create an Account',
      myBookings: 'My Bookings',
      myProfile: 'My Profile',
      editProfile: 'Edit Profile',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      edit: 'Edit',
      bookingHistory: 'Booking History',
      bookingHistoryPlaceholder: 'Your past and upcoming appointments will appear here.',
      updateSuccess: 'Profile updated successfully!',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      orContinueWith: 'Or continue with',
      continueWithGoogle: 'Continue with Google',
      form: {
        name: 'Full Name',
        email: 'Email Address',
        password: 'Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm New Password',
      },
      forgotPassword: 'Forgot Password?',
      forgotPasswordTitle: 'Forgot Your Password?',
      forgotPasswordDesc: "No problem. Enter your email address below and we'll send you a link to reset it.",
      sendResetLink: 'Send Reset Link',
      resetLinkSentTitle: 'Check Your Email',
      resetLinkSentDesc: 'If an account with that email exists, we have sent a password reset link.',
      resetLinkSentDemo: 'For this demo, click the button below to proceed.',
      resetPasswordDemoCta: 'Reset Your Password (Demo)',
      resetPasswordTitle: 'Set a New Password',
      resetPasswordDesc: 'Create a new, strong password for your account.',
      resetPassword: 'Reset Password',
      passwordResetSuccess: 'Your password has been reset successfully! You can now log in.',
      validation: {
        passwordMismatch: 'Passwords do not match.',
        passwordMinLength: 'Password must be at least 8 characters long.',
      }
    },
  },
  am: {
    header: {
      visitSite: 'ድህረገፅ ይጎብኙ',
      contact: 'ያግኙን',
      meetTheCEO: 'ዋና ስራ አስፈፃሚዋን ያግኙ',
      nav: {
        visitorSupport: 'የጎብኚዎች ድጋፍ',
      },
    },
    welcome: {
      title: 'ለስሜታዊ ፈውስ ወደ እርስዎ አስተማማኝ ቦታ እንኳን በደህና መጡ',
      description: "ሁሉም የአእምሮ ጤና ባለሙያዎች 'ዶክተር' ተብለው አይጠሩም - ፈውስ የሚከሰተው በርዕሱ ውስጥ ብቻ ሳይሆን በግንኙነት ውስጥ ነው። አካሄዳችን በጥልቅ መገኘት، በማስረጃ ላይ በተመሰረቱ መሳሪያዎች እና በተግባራዊ ጥበብ ላይ የተመሰረተ ነው።",
      ctaBook: 'አሁኑኑ ቀጠሮ ይያዙ',
      ctaExplore: 'አገልግሎቶቻችንን ይመልከቱ',
      chatbotGreeting: 'ሰላም! እኔ የሪሊፍ AI ረዳት ነኝ፣ በ{{language}} ልረዳዎ ዝግጁ ነኝ። ዛሬ እንዴት ልረዳዎት እችላለሁ? ስለአገልግሎቶቻችን፣ ስለቀጠሮ እና ሌሎችም ጥያቄዎችን መመለስ እችላለሁ።',
    },
    language: {
        english: 'እንግሊዝኛ',
        amharic: 'አማርኛ',
    },
    services: {
      title: 'የእኛ ሙያዊ አገልግሎቶች',
      description: 'ልዩ ፍላጎቶችዎን ለማሟላት የተዘጋጁ ሰፊ አገልግሎቶችን እናቀርባለን። ልምድ ያካበቱ ቴራፒስቶቻችን ወደ አእምሮአዊ ደህንነት በሚያደርጉት ጉዞ ላይ እርስዎን ለመምራት እዚህ አሉ።',
      priceFlexible: 'ዋጋው እንደ ሁኔታው ይለያያል',
       generalInquiry: {
          title: 'አጠቃላይ ጥያቄ',
          description: 'ስለአገልግሎቶቻችን ወይም እንዴት ልንረዳዎ እንደምንችል ለሚነሱ ጥያቄዎች።'
      }
    },
    service: {
        'artTherapy': { name: 'የሥነ-ጥበብ ሕክምና', short: 'በፈጠራ ዘዴዎች ስሜትን መግለጽ እና ማስተናገድ።', description: '...' },
        'speechTherapy': { name: 'የንግግር ሕክምና', short: 'የግንኙነት ክህሎቶችን ማሻሻል እና የንግግር እክሎችን ማከም።', description: '...' },
        'adultTherapy': { name: 'የአዋቂዎች ሕክምና', short: 'የህይወት ፈተናዎች ለሚገጥማቸው አዋቂዎች የግል ምክር።', description: '...' },
        'childBehavioralTherapy': { name: 'የልጆች የባህሪ ሕክምና', short: 'የባህሪ እና የስሜት ችግር ላለባቸው ህጻናት ድጋፍ።', description: '...' },
        'pregnancyEmotionRegulation': { name: 'የእርግዝና ስሜት መቆጣጠር', short: 'ለነፍሰ ጡር እና አዲስ እናቶች ስሜታዊ ድጋፍ።', description: '...' },
        'musicTherapy': { name: 'የሙዚቃ ሕክምና', short: 'አካላዊ፣ ስሜታዊ እና ማህበራዊ ፍላጎቶችን ለማሟላት ሙዚቃን መጠቀም።', description: '...' },
        'movementTherapy': { name: 'የእንቅስቃሴ ሕክምና', short: 'ለስሜታዊ እና አካላዊ ውህደት ዳንስ እና እንቅስቃሴን መጠቀም።', description: '...' },
        'groupTraining': { name: 'የቡድን ስልጠና', short: 'ለግል እና ለሙያዊ እድገት በይነተገናኝ ወርክሾፖች።', description: '...' },
        'ageTherapy': { name: 'ከእድሜ ጋር የተገናኘ ሕክምና', short: 'ከወጣትነት እስከ እርጅና ላሉ የተለያዩ የህይወት ደረጃዎች የተዘጋጀ ሕክምና።', description: '...' },
        'onlineTherapy': { name: 'የመስመር ላይ ሕክምና', short: 'ከየትኛውም ቦታ ምቹ እና ተደራሽ የሕክምና ክፍለ ጊዜዎች።', description: '...' },
        'visitorSupport': { name: 'የጎብኚዎች ድጋፍ እና መመሪያ', short: 'በአዲስ አበባ ለሚገኙ ጎብኚዎች አጠቃላይ ድጋፍ።', description: '...' },
    },
    faq: {
      title: 'ተደጋግመው የሚጠየቁ ጥያቄዎች',
      '1': { q: 'በመጀመሪያው የህክምና ክፍለ ጊዜ ምን መጠበቅ አለብኝ?', a: 'የመጀመሪያው ክፍለ ጊዜ እርስዎ እና ቴራፒስትዎ እርስ በርስ ለመተዋወቅ እድል ነው. ወደ ህክምና ምን እንዳመጣዎት, ታሪክዎን እና ግቦችዎን ይወያያሉ. እሱ የታመነ የህክምና ግንኙነትን ለመገንባት ያለመ የትብብር ሂደት ነው.' },
      '2': { q: 'የህክምና ክፍለ ጊዜ ለምን ያህል ጊዜ ይቆያል?', a: 'በተለምዶ የግለሰብ ክፍለ ጊዜዎች ለ 50 ደቂቃዎች ይቆያሉ. የጥንዶች እና የቤተሰብ ክፍለ ጊዜዎች እንደ ልዩ ፍላጎቶች እና ዝግጅቶች ከ60-75 ደቂቃዎች ሊረዝሙ ይችላሉ.' },
      '3': { q: 'በህክምና ውስጥ የማካፍለው ነገር ሚስጥራዊ ነው?', a: 'አዎ, ሚስጥራዊነት የህክምና መሰረት ነው. የሚያጋሩት ነገር ሁሉ የግል ነው, ቴራፒስትዎ በመጀመሪያው ክፍለ ጊዜዎ ከእርስዎ ጋር ከሚወያይባቸው ጥቂት ህጋዊ እና ስነ-ምግባራዊ ልዩ ሁኔታዎች በስተቀር.' },
      '4': { q: 'እንዴት ቀጠሮ መያዝ እችላለሁ?', a: 'በዋናው ገጻችን ላይ "አሁኑኑ ቀጠሮ ይያዙ" የሚለውን ቁልፍ ጠቅ በማድረግ ወይም አገልግሎት በመምረጥ እና የቀጠሮ ቁልፉን ጠቅ በማድረግ ቀጠሮ መያዝ ይችላሉ. ይህ የሚመርጡትን ሰዓት እና ቀን ለመጠየቅ ወደ ቅጽ ይወስደዎታል.' },
      '5': { q: 'የመስመር ላይ ክፍለ ጊዜዎችን ታቀርባላችሁ?', a: 'አዎ, ደንበኞቻችን የትም ቢሆኑ ተለዋዋጭ እና ተደራሽ እንክብካቤ ለመስጠት በአካል እና በመስመር ላይ (ቴሌሄልዝ) ክፍለ ጊዜዎችን እናቀርባለን.' },
    },
    testimonials: {
      title: 'ደንበኞቻችን ምን ይላሉ',
      '1': { quote: 'ያገኘሁት ድጋፍ ህይወትን የሚቀይር ነበር. ለመጀመሪያ ጊዜ እንደተሰማኝ እና እንደተረዳሁ ተሰማኝ. አገልግሎታቸውን በጣም እመክራለሁ.', author: 'አበበ ተ.' },
      '2': { quote: 'ቴራፒስታችን ጉዳዮቻችንን እንድንፈታ በመርዳት በሚያስደንቅ ሁኔታ የተካነ ነበር. ግንኙነታችን በጣም ተሻሽሏል.', author: 'ሄለን መ. እና ሳሙኤል በ.' },
      '3': { quote: 'በጣም ሙያዊ እና ሞቅ ያለ አካባቢ. ህክምና ለመጀመር አመንታ ነበርኩ, ነገር ግን የሪሊፍ ቡድን ምቹ እና ጠቃሚ ተሞክሮ እንዲሆን አድርጎታል.', author: 'ፋጡማ ሰ.' },
    },
    ceoProfile: {
      title: 'ከዋና ስራ አስፈፃሚያችን የተላከ መልዕክት',
      name: 'ወ/ሮ መቅደስ አየነ',
      role: 'መስራች እና ዋና ስራ አስፈፃሚ, ክሊኒካል ሳይኮሎጂስት',
      message: 'የሪሊፍ ተልእኳችን ግለሰቦችን የሚያበረታታ እና ማህበረሰባችንን የሚያጠናክር ተደራሽ, ከፍተኛ ጥራት ያለው የአእምሮ ጤና እንክብካቤ መስጠት ነው. በሰው መንፈስ ጥንካሬ እናምናለን እናም ወደ ደህንነት መንገድዎ ለመምራት ቆርጠናል.',
      stat1: 'የልምድ ዓመታት',
      stat1Value: '12+',
      stat2: 'ደስተኛ ደንበኞች',
      stat2Value: '5,000+',
      stat3: 'የስኬት መጠን',
      stat3Value: '98%',
      contact: 'ያግኙን',
    },
    footer: {
      aboutTitle: 'ስለ ሪሊፍ',
      aboutText: 'ሪሊፍ የስነ-ልቦና አገልግሎት በአዲስ አበባ ውስጥ የአእምሮ ጤና እንክብካቤን በማቅረብ, ደህንነትን እና የግል እድገትን ለማሳደግ ቁርጠኛ ነው.',
      quickLinksTitle: 'ፈጣን አገናኞች',
      linkServices: 'አገልግሎቶቻችን',
      linkVisitorSupport: 'የጎብኚዎች ድጋፍ',
      linkFaq: 'ተደጋጋሚ ጥያቄዎች',
      linkTestimonials: 'የደንበኞች አስተያየት',
      linkCeoProfile: 'የዋና ስራ አስፈፃሚ መገለጫ',
      contactTitle: 'ያግኙን',
      copyright: '© 2024 ሪሊፍ የስነ-ልቦና አገልግሎት. ሁሉም መብቶች የተጠበቁ ናቸው.',
    },
    contactModal: {
      title: 'ያግኙን',
      description: 'ጥያቄ አለዎት? ከታች ያለውን ቅጽ በመሙላት ያግኙን።',
      email: 'reliefefoyita57@gmail.com',
      phone: '+251932520157',
      form: {
        name: 'ሙሉ ስም',
        email: 'ኢሜይል አድራሻ',
        message: 'መልዕክት',
      },
      submit: 'መልዕክት ላክ',
      submitting: 'በመላክ ላይ...',
      submitError: 'መልዕክቱን መላክ አልተቻለም። እባክዎ ቆይተው እንደገና ይሞክሩ።',
      successTitle: 'መልዕክቱ ተልኳል!',
      successMessage: 'ስለደረሱን እናመሰግናለን። በተቻለ ፍጥነት ወደ እርስዎ እንመለሳለን።',
      validation: {
        nameRequired: 'ሙሉ ስም ያስፈልጋል።',
        emailRequired: 'ኢሜይል ያስፈልጋል።',
        emailInvalid: 'እባክዎ ትክክለኛ የኢሜይል አድራሻ ያስገቡ።',
        messageRequired: 'መልዕክት ያስፈልጋል።',
        messageMinLength: 'መልዕክቱ ቢያንስ 10 ቁምፊዎች መሆን አለበት።',
      }
    },
    visitorSupport: {
      title: 'ለጎብኚዎች አጠቃላይ ድጋፍ',
      subtitle: 'በአዲስ አበባ ውስጥ ከቤትዎ ውጭ ያለዎት ቤት',
      description: 'ለአጭር ጊዜ ጎብኚዎች ልዩ ድጋፍ እንሰጣለን, ቆይታዎ ምቹ, ደህንነቱ የተጠበቀ እና ስነ-ልቦናዊ ድጋፍ ያለው መሆኑን እናረጋግጣለን. ከመኖርያ ቤት እርዳታ እስከ ማህበረሰብ ውህደት ድረስ, እኛ ከጎንዎ ነን.',
      getStarted: 'ይጀምሩ',
      featureTitle: 'የምናቀርባቸው',
      accommodationTitle: 'መኖርያ',
      accommodationDesc: 'ደህንነቱ የተጠበቀ እና ተስማሚ መኖሪያ (ሆቴሎች, የእንግዳ ማረፊያ ቤቶች) ለማግኘት እርዳታ.',
      navigationTitle: 'የከተማ አሰሳ',
      navigationDesc: 'በትራንስፖርት, በአካባቢያዊ ምቹ ሁኔታዎች እና በባህላዊ ደንቦች ላይ መመሪያ.',
      psychologicalTitle: 'የስነ-ልቦና ድጋፍ',
      psychologicalDesc: 'ውጥረትን እና የባህል ድንጋጤን ለመቆጣጠር የባለሙያ ምክር ማግኘት.',
      communityTitle: 'የማህበረሰብ ውህደት',
      communityDesc: 'እንደ ቤት እንዲሰማዎት ከአካባቢያዊ ማህበረሰቦች እና ሀብቶች ጋር ማገናኘት.',
    },
    accommodationModal: {
        title: 'የመኖርያ ቤት እርዳታ',
        subtitle: 'በአዲስ አበባ ውስጥ ትክክለኛውን የመቆያ ቦታ እንዲያገኙ እንርዳዎ።',
        form: {
            name: 'ሙሉ ስም',
            email: 'ኢሜይል አድራሻ',
            accommodationType: 'የመኖርያ ቤት አይነት',
            types: {
                hotel: 'ሆቴል',
                guestHouse: 'የእንግዳ ማረፊያ',
                apartment: 'አፓርታማ',
            },
            duration: 'የመቆያ ጊዜ (ለምሳሌ, 2 ሳምንታት)',
            guests: 'የእንግዶች ብዛት',
            area: 'የሚመረጥ አካባቢ (በፍላጎት)',
            budget: 'በአንድ ሌሊት በጀት (በፍላጎት)',
            notes: 'ተጨማሪ ማስታወሻዎች ወይም ምርጫዎች',
        },
        submit: 'እርዳታ ይጠይቁ',
        successTitle: 'ጥያቄው ተልኳል!',
        successMessage: 'ስለጥያቄዎ እናመሰግናለን። ቡድናችን ፍላጎቶችዎን ገምግሞ በ24 ሰዓታት ውስጥ ከመኖርያ ቤት አማራጮች ጋር ይመለስልዎታል።',
        validation: {
            nameRequired: 'ሙሉ ስም ያስፈልጋል።',
            emailRequired: 'ኢሜይል ያስፈልጋል።',
            emailInvalid: 'እባክዎ ትክክለኛ የኢሜይል አድራሻ ያስገቡ።',
            accommodationTypeRequired: 'እባክዎ የመኖርያ ቤት አይነት ይምረጡ።',
            durationRequired: 'የመቆያ ጊዜ ያስፈልጋል።',
            guestsRequired: 'የእንግዶች ብዛት ያስፈልጋል።',
            guestsInvalid: 'እባክዎ ትክክለኛ የእንግዶች ብዛት ያስገቡ።',
        },
    },
    bookingModal: {
        title: 'ቀጠሮዎን ይያዙ',
        subtitle: 'የሚከተለውን አገልግሎት ለመያዝ እየሞከሩ ነው:',
        form: {
            name: 'ሙሉ ስም',
            email: 'ኢሜይል አድራሻ',
            phone: 'ስልክ ቁጥር (በፍላጎት)',
            date: 'የሚመርጡት ቀን',
            time: 'የሚመርጡት ሰዓት',
            notes: 'ለቴራፒስቱ ማስታወሻዎች (በፍላጎት)',
            sendEmailCopy: 'የማረጋገጫ ኢሜይል ላክልኝ',
        },
        submit: 'ቀጠሮ ይጠይቁ',
        submitting: 'በመላክ ላይ...',
        submitError: 'የቀጠሮ ጥያቄውን መላክ አልተቻለም። እባክዎ ቆይተው እንደገና ይሞክሩ።',
        successTitle: 'ጥያቄው ገብቷል!',
        successMessage: 'ስለ ቀጠሮ ጥያቄዎ እናመሰግናለን። የማረጋገጫ ኢሜይል ተልኳል። ቀጠሮዎን ለማረጋገጥ በቅርቡ እናገኝዎታለን።',
        close: 'ዝጋ',
        payment: {
            title: 'የክፍያ መረጃ',
            priceEtb: '1,500 ብር',
            priceUsd: '$30 ዶላር',
            methods: 'ተቀባይነት ያላቸው የክፍያ ዘዴዎች',
            telebirr: 'ቴሌብር',
            telebirrNumber: '0911223344',
            bank: 'የባንክ ማስተላለፍ',
            bankAccountName: 'ሪሊፍ ሳይኮሎጂካል ሰርቪስ ኃ/የተ/የግ/ማ',
            cbe: 'የኢትዮጵያ ንግድ ባንክ (CBE)',
            cbeAccount: '1000123456789',
            cbeSwift: 'CBETETAA',
            abyssinia: 'አቢሲኒያ ባንክ',
            abyssiniaAccount: '9876543210',
            abyssiniaSwift: 'ABYSETAA',
        },
        validation: {
            nameRequired: 'ሙሉ ስም ያስፈልጋል።',
            emailRequired: 'ኢሜይል ያስፈልጋል።',
            emailInvalid: 'እባክዎ ትክክለኛ የኢሜይል አድራሻ ያስገቡ።',
            dateRequired: 'እባክዎ ቀን ይምረጡ።',
            timeRequired: 'እባክዎ ሰዓት ይምረጡ።',
        }
    },
    categories: {
      all: 'ሁሉም',
      counseling: 'ምክር',
      therapy: 'ቴራፒ',
      training: 'ስልጠና',
    },
    adBanner: {
      text: 'ልዩ ቅናሽ፡ በመጀመሪያው የኦንላይን ቴራፒ ክፍለ ጊዜዎ 20% ቅናሽ ያግኙ! ለተወሰነ ጊዜ ብቻ።',
      cta: 'ተጨማሪ እወቅ',
    },
    auth: {
      login: 'ግባ',
      signup: 'ይመዝገቡ',
      logout: 'ውጣ',
      loading: 'በመጫን ላይ...',
      loginTitle: 'እንኳን ደህና መጡ',
      signupTitle: 'መለያ ይፍጠሩ',
      myBookings: 'የእኔ ቀጠሮዎች',
      myProfile: 'የእኔ መገለጫ',
      editProfile: 'መገለጫ አርትዕ',
      saveChanges: 'ለውጦችን አስቀምጥ',
      cancel: 'ሰርዝ',
      edit: 'አርትዕ',
      bookingHistory: 'የቀጠሮ ታሪክ',
      bookingHistoryPlaceholder: 'ያለፉ እና መጪ ቀጠሮዎችዎ እዚህ ይታያሉ።',
      updateSuccess: 'መገለጫ በተሳካ ሁኔታ ተዘምኗል!',
      noAccount: 'መለያ የለዎትም?',
      hasAccount: 'አስቀድመው መለያ አለዎት?',
      orContinueWith: 'ወይም በ',
      continueWithGoogle: 'በGoogle ይቀጥሉ',
      form: {
        name: 'ሙሉ ስም',
        email: 'ኢሜይል አድራሻ',
        password: 'የይለፍ ቃል',
        newPassword: 'አዲስ የይለፍ ቃል',
        confirmPassword: 'የይለፍ ቃል ያረጋግጡ',
      },
      forgotPassword: 'የይለፍ ቃል ረስተዋል?',
      forgotPasswordTitle: 'የይለፍ ቃልዎን ረስተዋል?',
      forgotPasswordDesc: 'ችግር የለም። ከታች የኢሜይል አድራሻዎን ያስገቡ እና እንደገና ለማስጀመር አገናኝ እንልክልዎታለን።',
      sendResetLink: 'የዳግም ማስጀመሪያ አገናኝ ላክ',
      resetLinkSentTitle: 'ኢሜይልዎን ያረጋግጡ',
      resetLinkSentDesc: 'በዚያ ኢሜይል መለያ ካለ፣ የይለፍ ቃል ዳግም ማስጀመሪያ አገናኝ ልከናል።',
      resetLinkSentDemo: 'ለዚህ ማሳያ፣ ለመቀጠል ከታች ያለውን ቁልፍ ይጫኑ።',
      resetPasswordDemoCta: 'የይለፍ ቃልዎን እንደገና ያስጀምሩ (ማሳያ)',
      resetPasswordTitle: 'አዲስ የይለፍ ቃል ያዘጋጁ',
      resetPasswordDesc: 'ለመለያዎ አዲስ፣ ጠንካራ የይለፍ ቃል ይፍጠሩ።',
      resetPassword: 'የይለፍ ቃል ዳግም አስጀምር',
      passwordResetSuccess: 'የይለፍ ቃልዎ በተሳካ ሁኔታ ዳግም ተጀምሯል! አሁን መግባት ይችላሉ።',
      validation: {
        passwordMismatch: 'የይለፍ ቃላት አይዛመዱም።',
        passwordMinLength: 'የይለፍ ቃል ቢያንስ 8 ቁምፊዎች መሆን አለበት።',
      }
    },
  }
};